
# APPLICATION

spring.application.name=event-booking-api
server.port=8080

# ACTIVE PROFILE
spring.profiles.active=dev
# JPA COMMON CONFIGURATION
spring.jpa.open-in-view=false
#JWT EXPIRATION
jwt.expiration=86400000